package hms;
//initialize the use packages.

import com.sun.glass.events.KeyEvent;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;

public class Doctor extends javax.swing.JFrame {

    //variables that use in this class
    private int empID; //employee ID of Doctor represent by using empID.
    private String university; //Doctor grautuated from which university indicated by this.
    private String special; // which subject that doctor specialist.

    public Doctor() {
        initComponents(); //constructor class for create all components
    }

    //take data from gui 
    public void setData() {
        String a = empIDText.getText(); //take the employee ID
        if (a.length() > 0) {
            //if the given an employee id take data
            empID = Integer.parseInt(a);

        }
        university = uniText.getText();
        special = subText.getText();

    }

    //reset method for reset all textFields.
    public void reset() {
        empIDText.setText("");
        uniText.setText("");
        subText.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        subText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        empIDText = new javax.swing.JTextField();
        uniText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Doctor Details"));

        jLabel1.setText("Emp ID:");

        empIDText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                empIDTextFocusLost(evt);
            }
        });
        empIDText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                empIDTextKeyTyped(evt);
            }
        });

        jLabel3.setText("specialist subjects:");

        jLabel2.setText("University:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(uniText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(empIDText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 51, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(empIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uniText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        registerBtn.setText("Register");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Delete");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(searchBtn)
                        .addGap(66, 66, 66)
                        .addComponent(registerBtn))
                    .addComponent(jButton2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(delBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetBtn)
                        .addGap(44, 44, 44))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerBtn)
                    .addComponent(delBtn)
                    .addComponent(searchBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        try {
            connection c = new connection(); //create an object of connection class
            Connection c1 = c.getConnect(); //create connection by using that connection
            Statement st = c1.createStatement(); //create statement type object

            this.setData();
            //take all lengths of inputs 
            int l = (int) Math.log10(empID) + 1;
            int l2 = university.length();
            int l3 = special.length();

            //take result set from doctor table which equal to employee ID given by user
            ResultSet rs = st.executeQuery("select * from doctor where empID='" + empID + "' ");

            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "empID already exist");//if the resultset is already exist means we cannot add new doctor.
                this.reset(); //so reset all details
            } else {
                String ty = "Doctor";
                Statement st2 = c1.createStatement();
                //take the resultset from employee table where employee id and field doctor.
                ResultSet rs2 = st2.executeQuery("select * from employee where empID='" + this.empID + "' and empType='" + ty + "'");
                if (rs2.next()) {
                    //if that result set exist check whether that length of the user match with the database length of variables
                    if (l < 6 || l2 < 31 || l3 < 41) {
                        //if length are okay add details to the doctor table and update it.
                        st.executeUpdate("insert into doctor(empID, university, subject) values('" + empID + "','" + university + "', '" + special + "')");
                        this.reset();
                    } else {
                        //if there input size more than the size where database variable size show error massage
                        JOptionPane.showMessageDialog(this, "input size error");
                    }
                } else {
                    //if there wasn't details in employee table remember user to register doctor in employee form.
                    JOptionPane.showMessageDialog(this, "First add Details in employee");
                }
            }
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_registerBtnActionPerformed

    private void empIDTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_empIDTextKeyTyped
        char vchar = evt.getKeyChar();
        if ((!(Character.isDigit(vchar))) || (vchar == KeyEvent.VK_BACKSPACE) || (vchar == KeyEvent.VK_DELETE)) {
            evt.consume();
            //make the employee id field to cannot input any character which not a number
        }
    }//GEN-LAST:event_empIDTextKeyTyped

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        try {
            connection c = new connection();//create an object of connection class
            Connection cn = c.getConnect();//make connection
            Statement st = cn.createStatement();

            this.setData();
            //take resultset from doctor tabel where employee ID exist
            ResultSet rs = st.executeQuery("select * from doctor where empID='" + this.empID + "'");
            if (rs.next()) {
                st.executeUpdate("delete from doctor where empID='" + this.empID + "'");
                st.executeUpdate("delete from employee where empID='" + this.empID + "'");
                JOptionPane.showMessageDialog(this, "Successfully deleted");
                this.reset();
                //if resultset exist delete from doctor and also from employee tables.

            } else {
                //if there wasn't a resultset show error message.
                JOptionPane.showMessageDialog(this, "No result to delete");

            }
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            connection c = new connection();//create an object of connection class
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();

            this.setData();
            if (empID > 0) {

                ResultSet rs = st.executeQuery("select * from doctor where empID='" + this.empID + "'");//take resultset from doctor table.
                if (rs.next()) {
                    uniText.setText(rs.getString("university"));//take the value from resultset and add it show it in form.
                    subText.setText(rs.getString("subject"));
                } else {
                    JOptionPane.showMessageDialog(this, "No search result found");//show error message when there wasn't a resultset.
                }
            } else {
                JOptionPane.showMessageDialog(null, "Add employee number!");
            }
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        this.reset();//reset all entry in textfield
    }//GEN-LAST:event_resetBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        employee e = new employee();//make an object of employee class
        e.setVisible(true);//open employee form
        this.dispose();//close this form
    }//GEN-LAST:event_jButton2ActionPerformed

    private void empIDTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_empIDTextFocusLost
        String cid = empIDText.getText();//take employee id field value
        int cd = 0;
        if (cid.length() > 0) {
            cd = Integer.parseInt(cid);//if that textfield not empty add to int variable
        }
        try {
            connection c = new connection();//create an object of connection class
            Connection cn = c.getConnect();//create a connection
            Statement st = cn.createStatement();
            if (cd > 0) {
                ResultSet rs = st.executeQuery("select * from employee where empID='" + cd + "'");//check whether that employee exist in employee table
                if (rs.next() == false) {
                    JOptionPane.showMessageDialog(this, "Invalid doctor ID!");//if there wasn't a value show error message
                    empIDText.setText("");
                } else {
                    String type = rs.getString("empType");
                    char[] arr = type.toCharArray();

                    String d = "Doctor";
                    char[] arr1 = d.toCharArray();

                    boolean val = Arrays.equals(arr, arr1);//check whehther that existing result set representing a doctor details

                    if (val == false) {
                        JOptionPane.showMessageDialog(this, "Invalid doctor ID!");//if it not a doctor detail show error message.
                        empIDText.setText("");
                    }
                }

            }
        } catch (Exception e) {
            System.out.print(e.getMessage());
        }
    }

    private void IDTExtFocusLost(java.awt.event.FocusEvent evt) {

    }//GEN-LAST:event_empIDTextFocusLost

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField empIDText;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton registerBtn;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField subText;
    private javax.swing.JTextField uniText;
    // End of variables declaration//GEN-END:variables
}
