/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hms;
import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Dhananjana
 */
public class medicalTest extends javax.swing.JFrame {

    public int tNo, PID, NID, charge, atndNO;
    public String des;
    
    public medicalTest() {
        initComponents();
    }
    
    public void getData()
    {
        String a = testNoText.getText();
        String b = pIdText.getText();
        String c = nIdText.getText();
        String d = chargeText.getText();
        String e = desText.getText();
        String f = patndText.getText();
        if(a.length()<6 && b.length()==9 && c.length()<6 && d.length()<5 && e.length()<51 )
        {
            tNo = Integer.parseInt(a);
            PID = Integer.parseInt(b);
            NID = Integer.parseInt(c);
            charge = Integer.parseInt(d);
            des = e;
            atndNO = Integer.parseInt(f);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Input size error");
        }
        
    }
    
    public void reset()
    {
        testNoText.setText("");
        pIdText.setText("");
        nIdText.setText("");
        chargeText.setText("");
        desText.setText("");
        patndText.setText("");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nIdText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        patndText = new javax.swing.JTextField();
        chargeText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pIdText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        desText = new javax.swing.JTextArea();
        testNoText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        searchBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        atndNoBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Medical test");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Test Details"));

        jLabel6.setText("charge:");

        nIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nIdTextFocusLost(evt);
            }
        });
        nIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nIdTextKeyTyped(evt);
            }
        });

        jLabel1.setText("Test no:");

        jLabel9.setText("Patnd No:");

        patndText.setEditable(false);
        patndText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                patndTextFocusLost(evt);
            }
        });

        chargeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chargeTextKeyTyped(evt);
            }
        });

        jLabel3.setText("description:");

        jLabel2.setText("Rs.");

        jLabel5.setText("nurse ID:");

        pIdText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pIdTextFocusLost(evt);
            }
        });
        pIdText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pIdTextKeyTyped(evt);
            }
        });

        desText.setColumns(20);
        desText.setRows(5);
        jScrollPane2.setViewportView(desText);

        testNoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testNoTextActionPerformed(evt);
            }
        });
        testNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                testNoTextKeyTyped(evt);
            }
        });

        jLabel4.setText("Patient ID:");

        jLabel7.setText("V");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(30, 30, 30))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chargeText, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(testNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patndText, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel7)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(testNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(pIdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(patndText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nIdText, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chargeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buttons"));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        addBtn.setText("ADD");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        atndNoBtn.setText("Get attendance");
        atndNoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atndNoBtnActionPerformed(evt);
            }
        });

        jButton1.setText("Add more Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(atndNoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(addBtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(searchBtn)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atndNoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(addBtn)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("retrieve data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testNoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testNoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_testNoTextActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try{
            connection c = new connection();
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();
            
            this.getData();
            
            
            ResultSet rs1 = st.executeQuery("select * from medTest where NIC='"+PID+"'");
            if(rs1.next()){
                int ad = Integer.parseInt(rs1.getString("PatndNo"));
                if(ad==atndNO)
                {
                    int money = Integer.parseInt(rs1.getString("charge"))+charge;
                    
                    st.executeUpdate("delete from medTest where NIC='"+PID+"'");
                    st.executeUpdate("insert into medTest(testNo, NIC, empID, description, charge, PatndNo) values('"+tNo+"','"+PID+"','"+NID+"','"+des+"','"+money+"','"+atndNO+"')");
                    JOptionPane.showMessageDialog(this, "Successfully updated");
                }
                else
                {
                    
                    st.executeUpdate("insert into medTest(testNo, NIC, empID, description, charge, PatndNo) values('"+tNo+"','"+PID+"','"+NID+"','"+des+"','"+charge+"','"+atndNO+"')");
                    
                    JOptionPane.showMessageDialog(this, "successfully added");
                    this.reset();
                }
            }
            else
            {
                st.executeUpdate("insert into medTest(testNo, NIC, empID, description, charge, PatndNo) values('"+tNo+"','"+PID+"','"+NID+"','"+des+"','"+charge+"','"+atndNO+"')");
                    
                JOptionPane.showMessageDialog(this, "successfully added");
                this.reset();
            }
            
            
            
            this.reset();
                    
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void pIdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pIdTextFocusLost
        String n = pIdText.getText();
        int num=0;
        if(n.length()!=0){
            num = Integer.parseInt(n);
        }
        try{
            connection c = new connection();
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();
            if(num!=0){
                ResultSet rs = st.executeQuery("select * from p_attendance where NIC='"+num+"'");
            
                if(rs.next()==false)
                {
                            JOptionPane.showMessageDialog(this, "Wrong patient ID");
                }
                
               
            }
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_pIdTextFocusLost

    private void nIdTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nIdTextFocusLost
        int nurID = Integer.parseInt(nIdText.getText());
        try{
            connection c = new connection();
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();
            
            ResultSet rs = st.executeQuery("select * from nurse where empID='"+nurID+"'");
            if(rs.next()==false)
            {
                JOptionPane.showMessageDialog(this, "Invalid employee ID");
            }
                
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_nIdTextFocusLost

    private void patndTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_patndTextFocusLost
        
    }//GEN-LAST:event_patndTextFocusLost

    private void atndNoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atndNoBtnActionPerformed
        try{
            connection c =  new connection();
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();
            int identy = Integer.parseInt(pIdText.getText());
            ResultSet rs = st.executeQuery("select * from p_attendance where NIC='"+identy+"'");
            if(rs.next())
            {
                patndText.setText(rs.getString("PatndNo"));
            }
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_atndNoBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try{
            connection c = new connection();
            Connection cn = c.getConnect();
            Statement st = cn.createStatement();
            
            int intger = Integer.parseInt(pIdText.getText());
            
            
            ResultSet rs = st.executeQuery("select * from medTest where NIC='"+intger+"'");
            if(rs.next()){
                desText.setText(rs.getString("description"));
                chargeText.setText(rs.getString("charge"));
                nIdText.setText(rs.getString("empID"));
                testNoText.setText(rs.getString("testNo"));
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No search result");
            }
        }
        catch(Exception e)
        {
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void testNoTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_testNoTextKeyTyped
        char vchar = evt.getKeyChar();
        if((!(Character.isDigit(vchar))) || (vchar == KeyEvent.VK_BACKSPACE ) || (vchar == KeyEvent.VK_DELETE)) 
        {
            evt.consume();
                        
        }
    }//GEN-LAST:event_testNoTextKeyTyped

    private void pIdTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pIdTextKeyTyped
        char vchar = evt.getKeyChar();
        if((!(Character.isDigit(vchar))) || (vchar == KeyEvent.VK_BACKSPACE ) || (vchar == KeyEvent.VK_DELETE)) 
        {
            evt.consume();
                        
        }
    }//GEN-LAST:event_pIdTextKeyTyped

    private void nIdTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nIdTextKeyTyped
        char vchar = evt.getKeyChar();
        if((!(Character.isDigit(vchar))) || (vchar == KeyEvent.VK_BACKSPACE ) || (vchar == KeyEvent.VK_DELETE)) 
        {
            evt.consume();
                        
        }
    }//GEN-LAST:event_nIdTextKeyTyped

    private void chargeTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chargeTextKeyTyped
        char vchar = evt.getKeyChar();
        if((!(Character.isDigit(vchar))) || (vchar == KeyEvent.VK_BACKSPACE ) || (vchar == KeyEvent.VK_DELETE)) 
        {
            evt.consume();
                        
        }
    }//GEN-LAST:event_chargeTextKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        patient p = new patient();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tableretrieve  e = new tableretrieve();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(medicalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(medicalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(medicalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(medicalTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new medicalTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton atndNoBtn;
    private javax.swing.JTextField chargeText;
    private javax.swing.JTextArea desText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nIdText;
    private javax.swing.JTextField pIdText;
    private javax.swing.JTextField patndText;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField testNoText;
    // End of variables declaration//GEN-END:variables
}
